# Chien luoc Close tren MA10 thi Buy; Close < MA10 thi Sell

### Buoc 1: Lay data
### Buoc 2: Xu ly data
### Buoc 2.1, 2.2: Buy_Signal, Sell_Signal
### Buoc 3: Show len chart
### Buoc 4: Day len Redis

# Buoc 1: Load data

### Viet luong tuong

In [1]:
import pandas as pd
import ccxt
from datetime import datetime, timedelta

# Khởi tạo kết nối đến sàn Binance
exchange = ccxt.binance()

# Định dạng ngày tháng
symbol = 'NEARUSDT'
from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm nay
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
timeframe = '1m' # 1m

since = exchange.parse8601(from_date + 'T00:00:00Z')
end = exchange.parse8601(to_date + 'T00:00:00Z')

# Lấy dữ liệu thị trường từ sàn Binance
# 1m
ohlcv = exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=1000)

# Chuyển dữ liệu thành DataFrame
data = pd.DataFrame(ohlcv, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='ms')         
data = data.rename(columns={'Timestamp': 'Datetime'})
data

               Datetime   Open   High    Low  Close   Volume
0   2025-02-27 00:00:00  3.024  3.030  3.024  3.027  11156.8
1   2025-02-27 00:01:00  3.027  3.027  3.022  3.022   1730.4
2   2025-02-27 00:02:00  3.021  3.031  3.021  3.031   5812.1
3   2025-02-27 00:03:00  3.032  3.037  3.032  3.035  17003.5
4   2025-02-27 00:04:00  3.034  3.034  3.024  3.024   5287.5
..                  ...    ...    ...    ...    ...      ...
894 2025-02-27 14:54:00  3.060  3.061  3.051  3.054  14194.1
895 2025-02-27 14:55:00  3.054  3.060  3.054  3.059   7711.2
896 2025-02-27 14:56:00  3.059  3.061  3.057  3.057   3458.5
897 2025-02-27 14:57:00  3.058  3.061  3.058  3.060   3982.1
898 2025-02-27 14:58:00  3.060  3.061  3.056  3.058   3564.7

[899 rows x 6 columns]

In [ ]:
# def loaddataBinance_FromTo(symbol, from_date, to_date, timeframe):
#     import pandas as pd
#     import ccxt
#     from datetime import datetime, timedelta

#     # Khởi tạo kết nối đến sàn Binance
#     exchange = ccxt.binance()

#     # Định dạng ngày tháng
#     since = exchange.parse8601(from_date + 'T00:00:00Z')
#     end = exchange.parse8601(to_date + 'T00:00:00Z')

#     # Lấy dữ liệu thị trường từ sàn Binance
#     # 1d
#     ohlcv = exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=1000)

#     # Chuyển dữ liệu thành DataFrame
#     data = pd.DataFrame(ohlcv, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
#     data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='ms')         
#     data = data.rename(columns={'Timestamp': 'Datetime'})

#     return data

In [3]:
# symbol = 'NEARUSDT'
# from_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
# to_date = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d')
# timeframe = '3m' # 1m

# # ##############################################Step 1: Lấy dữ liệu##############################################
# data = loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)
# print(data)

In [ ]:
# import pandas as pd
# import plotly.graph_objects as go
# import redis
# import numpy as np
# from datetime import datetime, timedelta

# # ##############################################Step 0: Các tham số để lấy dữ liệu###############################
# symbol = 'ETHUSDT'
# from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
# to_date = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d')
# timeframe = '1m' # 1m

# # ##############################################Step 1: Lấy dữ liệu##############################################
# data = loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)
# data

               Datetime     Open     High      Low    Close    Volume
0   2024-10-05 00:00:00  2414.41  2414.90  2414.40  2414.80   48.6916
1   2024-10-05 00:01:00  2414.80  2416.80  2414.80  2416.43  157.4245
2   2024-10-05 00:02:00  2416.43  2417.70  2416.42  2417.12   97.2674
3   2024-10-05 00:03:00  2417.12  2419.34  2417.12  2418.65  291.8041
4   2024-10-05 00:04:00  2418.66  2420.40  2418.66  2420.21  397.2193
..                  ...      ...      ...      ...      ...       ...
985 2024-10-05 16:25:00  2413.07  2414.99  2413.07  2414.80   50.8980
986 2024-10-05 16:26:00  2414.80  2414.80  2413.20  2413.71   50.1828
987 2024-10-05 16:27:00  2413.71  2413.92  2413.07  2413.07   51.8006
988 2024-10-05 16:28:00  2413.07  2413.72  2413.07  2413.16   39.8587
989 2024-10-05 16:29:00  2413.17  2414.00  2413.17  2414.00   25.6369

[990 rows x 6 columns]

# Chung ta co chien luoc: MA, ATR
### MA_FAST: Period 50
### MA_SLOW: Period 200
### ATR_Thresshole = 14
# Xác định tín hiệu mua
data['Buy_Signal'] = (data['MA_Fast'] >= data['MA_Slow']) & (data['ATR'] <= atr_threshold)
# Xác định tín hiệu bán
data['Sell_Signal'] = (data['MA_Fast'] < data['MA_Slow']) & (data['ATR'] <= atr_threshold)

!['MA ATR'](./FlowChart/flowchart_ma_atr_signal.png)

In [5]:
# ##############################################Step 2: Chiến lược##############################################  
# Đặt thời gian cho MA và ATR
ma_fast_period = 50
ma_slow_period = 200
atr_period = 14
atr_threshold = 50 # Xác định ngưỡng biến động thị trường

import talib
# Tính toán đường MA nhanh và MA chậm bằng TA-Lib
data['MA_Fast'] = talib.SMA(data['Close'], timeperiod=ma_fast_period)
data['MA_Slow'] = talib.SMA(data['Close'], timeperiod=ma_slow_period)
# Tính toán ATR bằng TA-Lib
# TA-Lib sẽ tự động tính toán True Range (TR) và Average True Range (ATR)
data['ATR'] = talib.ATR(data['High'], data['Low'], data['Close'], timeperiod=atr_period)

# Xác định tín hiệu mua
data['Buy_Signal'] = (data['MA_Fast'] >= data['MA_Slow']) & (data['ATR'] <= atr_threshold)
# Xác định tín hiệu bán
data['Sell_Signal'] = (data['MA_Fast'] < data['MA_Slow']) & (data['ATR'] <= atr_threshold)

In [6]:
data

,Datetime,Open,High,Low,Close,Volume,MA_Fast,MA_Slow,ATR,Buy_Signal,Sell_Signal
0,2024-10-05 00:00:00,2414.41,2414.90,2414.40,2414.80,48.6916,NaN,NaN,NaN,False,False
1,2024-10-05 00:01:00,2414.80,2416.80,2414.80,2416.43,157.4245,NaN,NaN,NaN,False,False
2,2024-10-05 00:02:00,2416.43,2417.70,2416.42,2417.12,97.2674,NaN,NaN,NaN,False,False
3,2024-10-05 00:03:00,2417.12,2419.34,2417.12,2418.65,291.8041,NaN,NaN,NaN,False,False
4,2024-10-05 00:04:00,2418.66,2420.40,2418.66,2420.21,397.2193,NaN,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...
985,2024-10-05 16:25:00,2413.07,2414.99,2413.07,2414.80,50.8980,2412.8148,2413.23150,1.406374,False,True
986,2024-10-05 16:26:00,2414.80,2414.80,2413.20,2413.71,50.1828,2412.8320,2413.19515,1.420204,False,True
987,2024-10-05 16:27:00,2413.71,2413.92,2413.07,2413.07,51.8006,2412.8674,2413.15835,1.379475,False,True
988,2024-10-05 16:28:00,2413.07,2413.72,2413.07,2413.16,39.8587,2412.8896,2413.11285,1.327370,False,True
989,2024-10-05 16:29:00,2413.17,2414.00,2413.17,2414.00,25.6369,2412.9274,2413.07180,1.292558,False,True

In [7]:
# data.to_csv('Buoi3_3 Chienluoc.csv')

In [8]:
import plotly.graph_objects as go
import plotly.subplots as sp  # Sử dụng plotly.subplots để tạo nhiều biểu đồ
import pandas as pd 

# Trực quan hóa dữ liệu (tùy chọn)
fig = go.Figure()

# Tạo subplot với 2 hàng
fig = sp.make_subplots(rows=2, cols=1, shared_xaxes=True, 
                       subplot_titles=('Price and Moving Averages', 'Average True Range (ATR)'))

# Thêm đường giá đóng cửa
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['Close'], mode='lines', name='Close Price'), row=1, col=1)

# Thêm đường MA_Fast và MA_Slow vào biểu đồ hàng đầu tiên
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['MA_Fast'], mode='lines', name='MA Fast'), row=1, col=1)
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['MA_Slow'], mode='lines', name='MA Slow'), row=1, col=1)

# Đánh dấu các tín hiệu mua và bán
fig.add_trace(go.Scatter(x=data[data['Buy_Signal'] == 1]['Datetime'], 
                         y=data[data['Buy_Signal'] == 1]['Close'], 
                         mode='markers', name='Buy Signal', marker=dict(color='green', size=10, symbol='triangle-up')), row=1, col=1)
fig.add_trace(go.Scatter(x=data[data['Sell_Signal'] == 1]['Datetime'], 
                         y=data[data['Sell_Signal'] == 1]['Close'], 
                         mode='markers', name='Sell Signal', marker=dict(color='red', size=10, symbol='triangle-down')), row=1, col=1)

# Thêm đường ATR vào biểu đồ hàng thứ hai
fig.add_trace(go.Scatter(x=data['Datetime'], y=data['ATR'], mode='lines', name='ATR'), row=2, col=1)

# Cấu hình và hiển thị biểu đồ
fig.update_layout(title='Moving Average Crossover and ATR Signals: ' + symbol , xaxis_title='Date', yaxis_title='Price', 
    height=800  # Tăng kích thước cao của biểu đồ lên 800
)

fig.update_xaxes(title_text='Date', row=2, col=1)
fig.update_yaxes(title_text='ATR', row=2, col=1)
fig.show()