# Co dinh Symbol

In [ ]:
from datetime import datetime, timedelta

import sys
sys.path.append("../Common")
import CommonBinanceDWH

print("Bat dau thuc hien:")
print(datetime.now())
symbol_list = ['BTCUSDT', 'ETHUSDT', 'XRPUSDT', 'BCH/USDT', 'LTCUSDT', 'ADAUSDT', 'DOTUSDT', 'LINKUSDT', 'XLMUSDT', 'XMRUSDT']
from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
data = CommonBinanceDWH.CommonBinanceDWH.loaddataBinance_FromTo_Split_ListSymbol(symbol_list, from_date, to_date, '1m')

print("Hoan thanh:")
print(datetime.now())

In [ ]:
data.to_csv('data.csv', index=False)

# Danh sach symbol tu San

In [ ]:
import ccxt
from datetime import datetime
# Khởi tạo kết nối đến sàn Binance
exchange = ccxt.binance()

# Lay toan bo symbol tren Binance
symbol_list = exchange.load_markets()
symbol_list

In [ ]:
# Loc lai lay symbol co kieu "USDT" va price > 1000
symbol_list = [symbol for symbol in symbol_list if symbol.endswith('USDT')]
symbol_list

In [4]:
from datetime import datetime, timedelta

import sys
sys.path.append("../Common")
import CommonBinanceDWH

print("Bat dau thuc hien:")
print(datetime.now())

symbol_list = ["BTCUSDT"]
from_date = (datetime.now() - timedelta(days=60)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')

data = CommonBinanceDWH.CommonBinanceDWH.loaddataBinance_FromTo_Split_ListSymbol_Limit(symbol_list, from_date, to_date, '1d', 60)

print("Hoan thanh:")
print(datetime.now())

Bat dau thuc hien:
2025-09-04 22:40:40.872737
Đang tải dữ liệu cho BTCUSDT...
ohlcv
[[1751760000000, 108198.12, 109700.0, 107800.01, 109203.84, 6447.607], [1751846400000, 109203.85, 109700.0, 107513.2, 108262.94, 9405.37601], [1751932800000, 108262.94, 109216.56, 107429.57, 108922.98, 9216.0208], [1752019200000, 108922.99, 111999.79, 108324.53, 111233.99, 17282.2865], [1752105600000, 111234.0, 116868.0, 110500.0, 116010.0, 24883.450665], [1752192000000, 116010.01, 118869.98, 115222.22, 117527.66, 25873.521148], [1752278400000, 117527.66, 118200.0, 116900.05, 117420.0, 8446.60437], [1752364800000, 117420.0, 119488.0, 117224.79, 119086.64, 9550.792947], [1752451200000, 119086.65, 123218.0, 118905.18, 119841.18, 27269.348877], [1752537600000, 119841.17, 119940.83, 115736.92, 117758.09, 32018.46083], [1752624000000, 117758.08, 120063.84, 117017.29, 118630.43, 17039.90851], [1752710400000, 118630.44, 120998.71, 117453.57, 119177.56, 15728.57651], [1752796800000, 119177.56, 120820.71, 116812.76, 117924.84, 19924.66266], [1752883200000, 117924.84, 118499.9, 117277.34, 117840.0, 6635.80306], [1752969600000, 117840.01, 118856.8, 116467.02, 117265.12, 12962.92889], [1753056000000, 117265.11, 119676.73, 116515.0, 117380.36, 17107.33128], [1753142400000, 117380.36, 120247.8, 116128.0, 119954.42, 20959.12973], [1753228800000, 119954.43, 120090.0, 117301.0, 118755.99, 14558.75083], [1753315200000, 118756.0, 119450.0, 117103.1, 118340.99, 15806.89043], [1753401600000, 118340.98, 118451.57, 114723.16, 117614.31, 38406.34873], [1753488000000, 117614.31, 118297.35, 117138.38, 117919.99, 6991.67206], [1753574400000, 117919.99, 119766.65, 117825.5, 119415.55, 9328.30919], [1753660800000, 119415.56, 119800.0, 117427.5, 118062.32, 13961.74754], [1753747200000, 118062.32, 119273.36, 116950.75, 117950.76, 15137.93445], [1753833600000, 117950.75, 118792.0, 115796.23, 117840.3, 15586.73631], [1753920000000, 117840.29, 118922.45, 115500.0, 115764.08, 17010.0073], [1754006400000, 115764.07, 116052.0, 112722.58, 113297.93, 24487.10206], [1754092800000, 113297.92, 114063.49, 112003.0, 112546.35, 11507.33428], [1754179200000, 112546.35, 114799.97, 111920.0, 114208.8, 7397.76046], [1754265600000, 114208.81, 115720.0, 114107.6, 115055.03, 9667.67916], [1754352000000, 115055.03, 115127.81, 112650.0, 114129.75, 12042.79078], [1754438400000, 114129.75, 115716.0, 113355.13, 114992.27, 9761.15318], [1754524800000, 114992.27, 117621.0, 114259.0, 117472.01, 13468.56263], [1754611200000, 117472.02, 117630.0, 115878.71, 116674.74, 10045.31278], [1754697600000, 116674.74, 117944.05, 116299.13, 116462.25, 9514.13144], [1754784000000, 116462.25, 119311.11, 116460.63, 119294.01, 14322.77073], [1754870400000, 119294.27, 122335.16, 118050.11, 118686.0, 26494.33429], [1754956800000, 118686.0, 120324.43, 118207.47, 120134.08, 16720.10893], [1755043200000, 120134.09, 123667.79, 118920.92, 123306.43, 23210.07102], [1755129600000, 123306.44, 124474.0, 117180.0, 118295.09, 27980.947586], [1755216000000, 118295.09, 119216.82, 116803.99, 117342.05, 13623.33874], [1755302400000, 117342.04, 117898.99, 117143.98, 117380.66, 6393.68117], [1755388800000, 117380.66, 118575.0, 117172.21, 117405.01, 5898.64192], [1755475200000, 117405.01, 117543.75, 114640.14, 116227.05, 17745.93954], [1755561600000, 116227.05, 116725.69, 112732.58, 112872.94, 18065.47424], [1755648000000, 112872.95, 114615.38, 112380.0, 114271.24, 15636.34194], [1755734400000, 114271.23, 114821.76, 112015.67, 112500.0, 10839.69235], [1755820800000, 112500.0, 117429.05, 111684.79, 116935.99, 23128.09037], [1755907200000, 116936.0, 117030.0, 114560.0, 115438.05, 11329.36197], [1755993600000, 115438.06, 115666.68, 110680.0, 113493.59, 21175.98462], [1756080000000, 113493.59, 113667.28, 109274.1, 110111.98, 25182.79379], [1756166400000, 110111.98, 112371.0, 108666.66, 111763.22, 18452.43877], [1756252800000, 111763.22, 112625.0, 110345.42, 111262.01, 13392.60875], [1756339200000, 111262.01, 113485.9, 110862.42, 112566.9, 11104.27744], [1756425600000, 112566.9, 112638.64, 107463.9, 108377.4, 22580.31045], [1756512000000, 108377.4, 108926.15, 107350.1, 108816.33, 10708.39159], [1756598400000, 108816.33, 109480.02, 108076.93, 108246.35, 9489.51596], [1756684800000, 108246.36, 109912.4, 107255.0, 109237.42, 16053.60219], [1756771200000, 109237.43, 111771.52, 108393.39, 111240.01, 18510.28756], [1756857600000, 111240.01, 112575.27, 110528.71, 111705.71, 11773.72084]]
data truoc khi them Symbol
     Datetime       Open       High        Low      Close        Volume
0  2025-07-06  108198.12  109700.00  107800.01  109203.84   6447.607000
1  2025-07-07  109203.85  109700.00  107513.20  108262.94   9405.376010
2  2025-07-08  108262.94  109216.56  107429.57  108922.98   9216.020800
3  2025-07-09  108922.99  111999.79  108324.53  111233.99  17282.286500
4  2025-07-10  111234.00  116868.00  110500.00  116010.00  24883.450665
5  2025-07-11  116010.01  118869.98  115222.22  117527.66  25873.521148
6  2025-07-12  117527.66  118200.00  116900.05  117420.00   8446.604370
7  2025-07-13  117420.00  119488.00  117224.79  119086.64   9550.792947
8  2025-07-14  119086.65  123218.00  118905.18  119841.18  27269.348877
9  2025-07-15  119841.17  119940.83  115736.92  117758.09  32018.460830
10 2025-07-16  117758.08  120063.84  117017.29  118630.43  17039.908510
11 2025-07-17  118630.44  120998.71  117453.57  119177.56  15728.576510
12 2025-07-18  119177.56  120820.71  116812.76  117924.84  19924.662660
13 2025-07-19  117924.84  118499.90  117277.34  117840.00   6635.803060
14 2025-07-20  117840.01  118856.80  116467.02  117265.12  12962.928890
15 2025-07-21  117265.11  119676.73  116515.00  117380.36  17107.331280
16 2025-07-22  117380.36  120247.80  116128.00  119954.42  20959.129730
17 2025-07-23  119954.43  120090.00  117301.00  118755.99  14558.750830
18 2025-07-24  118756.00  119450.00  117103.10  118340.99  15806.890430
19 2025-07-25  118340.98  118451.57  114723.16  117614.31  38406.348730
20 2025-07-26  117614.31  118297.35  117138.38  117919.99   6991.672060
21 2025-07-27  117919.99  119766.65  117825.50  119415.55   9328.309190
22 2025-07-28  119415.56  119800.00  117427.50  118062.32  13961.747540
23 2025-07-29  118062.32  119273.36  116950.75  117950.76  15137.934450
24 2025-07-30  117950.75  118792.00  115796.23  117840.30  15586.736310
25 2025-07-31  117840.29  118922.45  115500.00  115764.08  17010.007300
26 2025-08-01  115764.07  116052.00  112722.58  113297.93  24487.102060
27 2025-08-02  113297.92  114063.49  112003.00  112546.35  11507.334280
28 2025-08-03  112546.35  114799.97  111920.00  114208.80   7397.760460
29 2025-08-04  114208.81  115720.00  114107.60  115055.03   9667.679160
30 2025-08-05  115055.03  115127.81  112650.00  114129.75  12042.790780
31 2025-08-06  114129.75  115716.00  113355.13  114992.27   9761.153180
32 2025-08-07  114992.27  117621.00  114259.00  117472.01  13468.562630
33 2025-08-08  117472.02  117630.00  115878.71  116674.74  10045.312780
34 2025-08-09  116674.74  117944.05  116299.13  116462.25   9514.131440
35 2025-08-10  116462.25  119311.11  116460.63  119294.01  14322.770730
36 2025-08-11  119294.27  122335.16  118050.11  118686.00  26494.334290
37 2025-08-12  118686.00  120324.43  118207.47  120134.08  16720.108930
38 2025-08-13  120134.09  123667.79  118920.92  123306.43  23210.071020
39 2025-08-14  123306.44  124474.00  117180.00  118295.09  27980.947586
40 2025-08-15  118295.09  119216.82  116803.99  117342.05  13623.338740
41 2025-08-16  117342.04  117898.99  117143.98  117380.66   6393.681170
42 2025-08-17  117380.66  118575.00  117172.21  117405.01   5898.641920
43 2025-08-18  117405.01  117543.75  114640.14  116227.05  17745.939540
44 2025-08-19  116227.05  116725.69  112732.58  112872.94  18065.474240
45 2025-08-20  112872.95  114615.38  112380.00  114271.24  15636.341940
46 2025-08-21  114271.23  114821.76  112015.67  112500.00  10839.692350
47 2025-08-22  112500.00  117429.05  111684.79  116935.99  23128.090370
48 2025-08-23  116936.00  117030.00  114560.00  115438.05  11329.361970
49 2025-08-24  115438.06  115666.68  110680.00  113493.59  21175.984620
50 2025-08-25  113493.59  113667.28  109274.10  110111.98  25182.793790
51 2025-08-26  110111.98  112371.00  108666.66  111763.22  18452.438770
52 2025-08-27  111763.22  112625.00  110345.42  111262.01  13392.608750
53 2025-08-28  111262.01  113485.90  110862.42  112566.90  11104.277440
54 2025-08-29  112566.90  112638.64  107463.90  108377.40  22580.310450
55 2025-08-30  108377.40  108926.15  107350.10  108816.33  10708.391590
56 2025-08-31  108816.33  109480.02  108076.93  108246.35   9489.515960
57 2025-09-01  108246.36  109912.40  107255.00  109237.42  16053.602190
58 2025-09-02  109237.43  111771.52  108393.39  111240.01  18510.287560
59 2025-09-03  111240.01  112575.27  110528.71  111705.71  11773.720840
data sau khi them Symbol
     Datetime       Open       High        Low      Close        Volume  \
0  2025-07-06  108198.12  109700.00  107800.01  109203.84   6447.607000
1  2025-07-07  109203.85  109700.00  107513.20  108262.94   9405.376010
2  2025-07-08  108262.94  109216.56  107429.57  108922.98   9216.020800
3  2025-07-09  108922.99  111999.79  108324.53  111233.99  17282.286500
4  2025-07-10  111234.00  116868.00  110500.00  116010.00  24883.450665
5  2025-07-11  116010.01  118869.98  115222.22  117527.66  25873.521148
6  2025-07-12  117527.66  118200.00  116900.05  117420.00   8446.604370
7  2025-07-13  117420.00  119488.00  117224.79  119086.64   9550.792947
8  2025-07-14  119086.65  123218.00  118905.18  119841.18  27269.348877
9  2025-07-15  119841.17  119940.83  115736.92  117758.09  32018.460830
10 2025-07-16  117758.08  120063.84  117017.29  118630.43  17039.908510
11 2025-07-17  118630.44  120998.71  117453.57  119177.56  15728.576510
12 2025-07-18  119177.56  120820.71  116812.76  117924.84  19924.662660
13 2025-07-19  117924.84  118499.90  117277.34  117840.00   6635.803060
14 2025-07-20  117840.01  118856.80  116467.02  117265.12  12962.928890
15 2025-07-21  117265.11  119676.73  116515.00  117380.36  17107.331280
16 2025-07-22  117380.36  120247.80  116128.00  119954.42  20959.129730
17 2025-07-23  119954.43  120090.00  117301.00  118755.99  14558.750830
18 2025-07-24  118756.00  119450.00  117103.10  118340.99  15806.890430
19 2025-07-25  118340.98  118451.57  114723.16  117614.31  38406.348730
20 2025-07-26  117614.31  118297.35  117138.38  117919.99   6991.672060
21 2025-07-27  117919.99  119766.65  117825.50  119415.55   9328.309190
22 2025-07-28  119415.56  119800.00  117427.50  118062.32  13961.747540
23 2025-07-29  118062.32  119273.36  116950.75  117950.76  15137.934450
24 2025-07-30  117950.75  118792.00  115796.23  117840.30  15586.736310
25 2025-07-31  117840.29  118922.45  115500.00  115764.08  17010.007300
26 2025-08-01  115764.07  116052.00  112722.58  113297.93  24487.102060
27 2025-08-02  113297.92  114063.49  112003.00  112546.35  11507.334280
28 2025-08-03  112546.35  114799.97  111920.00  114208.80   7397.760460
29 2025-08-04  114208.81  115720.00  114107.60  115055.03   9667.679160
30 2025-08-05  115055.03  115127.81  112650.00  114129.75  12042.790780
31 2025-08-06  114129.75  115716.00  113355.13  114992.27   9761.153180
32 2025-08-07  114992.27  117621.00  114259.00  117472.01  13468.562630
33 2025-08-08  117472.02  117630.00  115878.71  116674.74  10045.312780
34 2025-08-09  116674.74  117944.05  116299.13  116462.25   9514.131440
35 2025-08-10  116462.25  119311.11  116460.63  119294.01  14322.770730
36 2025-08-11  119294.27  122335.16  118050.11  118686.00  26494.334290
37 2025-08-12  118686.00  120324.43  118207.47  120134.08  16720.108930
38 2025-08-13  120134.09  123667.79  118920.92  123306.43  23210.071020
39 2025-08-14  123306.44  124474.00  117180.00  118295.09  27980.947586
40 2025-08-15  118295.09  119216.82  116803.99  117342.05  13623.338740
41 2025-08-16  117342.04  117898.99  117143.98  117380.66   6393.681170
42 2025-08-17  117380.66  118575.00  117172.21  117405.01   5898.641920
43 2025-08-18  117405.01  117543.75  114640.14  116227.05  17745.939540
44 2025-08-19  116227.05  116725.69  112732.58  112872.94  18065.474240
45 2025-08-20  112872.95  114615.38  112380.00  114271.24  15636.341940
46 2025-08-21  114271.23  114821.76  112015.67  112500.00  10839.692350
47 2025-08-22  112500.00  117429.05  111684.79  116935.99  23128.090370
48 2025-08-23  116936.00  117030.00  114560.00  115438.05  11329.361970
49 2025-08-24  115438.06  115666.68  110680.00  113493.59  21175.984620
50 2025-08-25  113493.59  113667.28  109274.10  110111.98  25182.793790
51 2025-08-26  110111.98  112371.00  108666.66  111763.22  18452.438770
52 2025-08-27  111763.22  112625.00  110345.42  111262.01  13392.608750
53 2025-08-28  111262.01  113485.90  110862.42  112566.90  11104.277440
54 2025-08-29  112566.90  112638.64  107463.90  108377.40  22580.310450
55 2025-08-30  108377.40  108926.15  107350.10  108816.33  10708.391590
56 2025-08-31  108816.33  109480.02  108076.93  108246.35   9489.515960
57 2025-09-01  108246.36  109912.40  107255.00  109237.42  16053.602190
58 2025-09-02  109237.43  111771.52  108393.39  111240.01  18510.287560
59 2025-09-03  111240.01  112575.27  110528.71  111705.71  11773.720840

     Symbol
0   BTCUSDT
1   BTCUSDT
2   BTCUSDT
3   BTCUSDT
4   BTCUSDT
5   BTCUSDT
6   BTCUSDT
7   BTCUSDT
8   BTCUSDT
9   BTCUSDT
10  BTCUSDT
11  BTCUSDT
12  BTCUSDT
13  BTCUSDT
14  BTCUSDT
15  BTCUSDT
16  BTCUSDT
17  BTCUSDT
18  BTCUSDT
19  BTCUSDT
20  BTCUSDT
21  BTCUSDT
22  BTCUSDT
23  BTCUSDT
24  BTCUSDT
25  BTCUSDT
26  BTCUSDT
27  BTCUSDT
28  BTCUSDT
29  BTCUSDT
30  BTCUSDT
31  BTCUSDT
32  BTCUSDT
33  BTCUSDT
34  BTCUSDT
35  BTCUSDT
36  BTCUSDT
37  BTCUSDT
38  BTCUSDT
39  BTCUSDT
40  BTCUSDT
41  BTCUSDT
42  BTCUSDT
43  BTCUSDT
44  BTCUSDT
45  BTCUSDT
46  BTCUSDT
47  BTCUSDT
48  BTCUSDT
49  BTCUSDT
50  BTCUSDT
51  BTCUSDT
52  BTCUSDT
53  BTCUSDT
54  BTCUSDT
55  BTCUSDT
56  BTCUSDT
57  BTCUSDT
58  BTCUSDT
59  BTCUSDT
ohlcv
[[1756944000000, 111705.72, 112180.0, 109329.12, 109474.34, 7935.44652]]
data truoc khi them Symbol
    Datetime       Open      High        Low      Close      Volume
0 2025-09-04  111705.72  112180.0  109329.12  109474.34  7935.44652
data sau khi them Symbol
    Datetime       Open      High        Low      Close      Volume   Symbol
0 2025-09-04  111705.72  112180.0  109329.12  109474.34  7935.44652  BTCUSDT
Hoàn thành tải dữ liệu cho BTCUSDT: 61 records
Hoan thanh:
2025-09-04 22:40:44.953787

In [5]:
data

,Datetime,Open,High,Low,Close,Volume,Symbol
0,2025-07-06,108198.12,109700.00,107800.01,109203.84,6447.607000,BTCUSDT
1,2025-07-07,109203.85,109700.00,107513.20,108262.94,9405.376010,BTCUSDT
2,2025-07-08,108262.94,109216.56,107429.57,108922.98,9216.020800,BTCUSDT
3,2025-07-09,108922.99,111999.79,108324.53,111233.99,17282.286500,BTCUSDT
4,2025-07-10,111234.00,116868.00,110500.00,116010.00,24883.450665,BTCUSDT
...,...,...,...,...,...,...,...
56,2025-08-31,108816.33,109480.02,108076.93,108246.35,9489.515960,BTCUSDT
57,2025-09-01,108246.36,109912.40,107255.00,109237.42,16053.602190,BTCUSDT
58,2025-09-02,109237.43,111771.52,108393.39,111240.01,18510.287560,BTCUSDT
59,2025-09-03,111240.01,112575.27,110528.71,111705.71,11773.720840,BTCUSDT
60,2025-09-04,111705.72,112180.00,109329.12,109474.34,7935.446520,BTCUSDT

In [7]:
import talib	
data["MA20"] = talib.SMA(data["Close"], timeperiod=20)
data["MA50"] = talib.SMA(data["Close"], timeperiod=50)
data

,Datetime,Open,High,Low,Close,Volume,Symbol,MA20,MA50
0,2025-07-06,108198.12,109700.00,107800.01,109203.84,6447.607000,BTCUSDT,NaN,NaN
1,2025-07-07,109203.85,109700.00,107513.20,108262.94,9405.376010,BTCUSDT,NaN,NaN
2,2025-07-08,108262.94,109216.56,107429.57,108922.98,9216.020800,BTCUSDT,NaN,NaN
3,2025-07-09,108922.99,111999.79,108324.53,111233.99,17282.286500,BTCUSDT,NaN,NaN
4,2025-07-10,111234.00,116868.00,110500.00,116010.00,24883.450665,BTCUSDT,NaN,NaN
...,...,...,...,...,...,...,...,...,...
56,2025-08-31,108816.33,109480.02,108076.93,108246.35,9489.515960,BTCUSDT,114337.3185,116121.7688
57,2025-09-01,108246.36,109912.40,107255.00,109237.42,16053.602190,BTCUSDT,113792.4855,115924.7844
58,2025-09-02,109237.43,111771.52,108393.39,111240.01,18510.287560,BTCUSDT,113189.1645,115752.7610
59,2025-09-03,111240.01,112575.27,110528.71,111705.71,11773.720840,BTCUSDT,112859.6955,115631.7134
60,2025-09-04,111705.72,112180.00,109329.12,109474.34,7935.446520,BTCUSDT,112466.3100,115448.5916

In [8]:
data["Buy_Signal"] = (data["MA20"] > data["MA50"]) 
data["Sell_Signal"] = (data["MA20"] < data["MA50"]) 
data

,Datetime,Open,High,Low,Close,Volume,Symbol,MA20,MA50,Buy_Signal,Sell_Signal
0,2025-07-06,108198.12,109700.00,107800.01,109203.84,6447.607000,BTCUSDT,NaN,NaN,False,False
1,2025-07-07,109203.85,109700.00,107513.20,108262.94,9405.376010,BTCUSDT,NaN,NaN,False,False
2,2025-07-08,108262.94,109216.56,107429.57,108922.98,9216.020800,BTCUSDT,NaN,NaN,False,False
3,2025-07-09,108922.99,111999.79,108324.53,111233.99,17282.286500,BTCUSDT,NaN,NaN,False,False
4,2025-07-10,111234.00,116868.00,110500.00,116010.00,24883.450665,BTCUSDT,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...,...
56,2025-08-31,108816.33,109480.02,108076.93,108246.35,9489.515960,BTCUSDT,114337.3185,116121.7688,False,True
57,2025-09-01,108246.36,109912.40,107255.00,109237.42,16053.602190,BTCUSDT,113792.4855,115924.7844,False,True
58,2025-09-02,109237.43,111771.52,108393.39,111240.01,18510.287560,BTCUSDT,113189.1645,115752.7610,False,True
59,2025-09-03,111240.01,112575.27,110528.71,111705.71,11773.720840,BTCUSDT,112859.6955,115631.7134,False,True
60,2025-09-04,111705.72,112180.00,109329.12,109474.34,7935.446520,BTCUSDT,112466.3100,115448.5916,False,True

In [9]:
last_row = data.iloc[-2]
last_row

Datetime       2025-09-03 00:00:00
Open                     111240.01
High                     112575.27
Low                      110528.71
Close                    111705.71
Volume                 11773.72084
Symbol                     BTCUSDT
MA20                   112859.6955
MA50                   115631.7134
Buy_Signal                   False
Sell_Signal                   True
Name: 59, dtype: object

In [ ]:
# Day last_row qua redis

# Doji

In [ ]:
# Kiem tra co phai doji