# Load data

In [5]:
import sys
sys.path.append("../Common")

import CommonYFinance, CommonBinance, CommonMT5, CommonBacktest, CommonSSI

In [9]:
symbol = 'VCB'
from_date = '2025-08-01'
to_date = '2025-11-07'
interval = '1d'
# data = CommonYFinance.CommonYFinance.loaddataYFinance(symbol, from_date, to_date, interval)
data = CommonSSI.CommonSSI.loaddataSSI(symbol, from_date, to_date)

daily_ohlc(symbol='VCB', fromDate='01/08/2025', toDate='07/11/2025', pageIndex=1, pageSize=100, ascending=True)
{'data': [{'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '01/08/2025', 'Time': None, 'Open': '59866', 'High': '60164', 'Low': '59270', 'Close': '59767', 'Volume': '4751600', 'Value': '285499090000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '04/08/2025', 'Time': None, 'Open': '59667', 'High': '60958', 'Low': '59568', 'Close': '60660', 'Volume': '4462400', 'Value': '271298380000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '05/08/2025', 'Time': None, 'Open': '61057', 'High': '63241', 'Low': '60759', 'Close': '61057', 'Volume': '18590000', 'Value': '1159664360000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '06/08/2025', 'Time': None, 'Open': '61653', 'High': '62348', 'Low': '61454', 'Close': '61851', 'Volume': '4677500', 'Value': '291502420000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '07/08/2025', 'Time': None, 'Open': '62447', 'High': '62447', 'Low': '60859', 'Close': '61256', 'Volume': '9498700', 'Value': '587678430000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '08/08/2025', 'Time': None, 'Open': '61752', 'High': '62844', 'Low': '61156', 'Close': '61454', 'Volume': '10679800', 'Value': '665503890000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '11/08/2025', 'Time': None, 'Open': '61653', 'High': '62745', 'Low': '61653', 'Close': '62050', 'Volume': '7266300', 'Value': '454515450000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '12/08/2025', 'Time': None, 'Open': '62348', 'High': '64333', 'Low': '62249', 'Close': '62546', 'Volume': '12129000', 'Value': '770169850000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '13/08/2025', 'Time': None, 'Open': '63043', 'High': '63142', 'Low': '61554', 'Close': '62050', 'Volume': '7519800', 'Value': '470654320000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '14/08/2025', 'Time': None, 'Open': '63241', 'High': '65823', 'Low': '62844', 'Close': '64731', 'Volume': '19003100', 'Value': '1227651390000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '15/08/2025', 'Time': None, 'Open': '66915', 'High': '67014', 'Low': '63738', 'Close': '63837', 'Volume': '16667800', 'Value': '1098675630000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '18/08/2025', 'Time': None, 'Open': '64333', 'High': '65128', 'Low': '63539', 'Close': '64036', 'Volume': '8297300', 'Value': '536929470000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '19/08/2025', 'Time': None, 'Open': '64036', 'High': '64929', 'Low': '63738', 'Close': '63738', 'Volume': '9191400', 'Value': '593569360000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '20/08/2025', 'Time': None, 'Open': '64036', 'High': '64135', 'Low': '61752', 'Close': '62546', 'Volume': '10537600', 'Value': '667369550000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '21/08/2025', 'Time': None, 'Open': '62844', 'High': '64532', 'Low': '62844', 'Close': '63738', 'Volume': '9639300', 'Value': '620318450000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '22/08/2025', 'Time': None, 'Open': '63539', 'High': '66716', 'Low': '63241', 'Close': '64135', 'Volume': '18944300', 'Value': '1245865980000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '25/08/2025', 'Time': None, 'Open': '65326', 'High': '65326', 'Low': '62944', 'Close': '63142', 'Volume': '7750800', 'Value': '498260000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '26/08/2025', 'Time': None, 'Open': '63142', 'High': '64532', 'Low': '62447', 'Close': '64135', 'Volume': '7988400', 'Value': '507780740000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '27/08/2025', 'Time': None, 'Open': '64532', 'High': '68602', 'Low': '64532', 'Close': '68602', 'Volume': '31048100', 'Value': '2128073130000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '28/08/2025', 'Time': None, 'Open': '69000', 'High': '70092', 'Low': '68205', 'Close': '68503', 'Volume': '8799400', 'Value': '611089560000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '29/08/2025', 'Time': None, 'Open': '68702', 'High': '69595', 'Low': '68007', 'Close': '68106', 'Volume': '14696100', 'Value': '1017860550000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '03/09/2025', 'Time': None, 'Open': '68305', 'High': '68305', 'Low': '66518', 'Close': '66518', 'Volume': '14216900', 'Value': '962297890000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '04/09/2025', 'Time': None, 'Open': '67014', 'High': '68503', 'Low': '66418', 'Close': '68404', 'Volume': '8942100', 'Value': '607466390000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '05/09/2025', 'Time': None, 'Open': '69000', 'High': '69099', 'Low': '67014', 'Close': '67014', 'Volume': '11047800', 'Value': '759069220000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '08/09/2025', 'Time': None, 'Open': '66617', 'High': '67014', 'Low': '64830', 'Close': '64830', 'Volume': '11249800', 'Value': '745660080000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '09/09/2025', 'Time': None, 'Open': '65028', 'High': '65723', 'Low': '64036', 'Close': '64433', 'Volume': '6192300', 'Value': '402660300000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '10/09/2025', 'Time': None, 'Open': '65128', 'High': '65525', 'Low': '64333', 'Close': '65326', 'Volume': '5006400', 'Value': '326945700000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '11/09/2025', 'Time': None, 'Open': '65128', 'High': '65525', 'Low': '63738', 'Close': '65227', 'Volume': '6349100', 'Value': '413050950000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '12/09/2025', 'Time': None, 'Open': '65723', 'High': '65723', 'Low': '64532', 'Close': '65326', 'Volume': '5694200', 'Value': '373462790000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '15/09/2025', 'Time': None, 'Open': '65525', 'High': '65525', 'Low': '65028', 'Close': '65326', 'Volume': '5367400', 'Value': '352711800000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '16/09/2025', 'Time': None, 'Open': '65525', 'High': '66120', 'Low': '65128', 'Close': '65128', 'Volume': '6765400', 'Value': '447031130000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '17/09/2025', 'Time': None, 'Open': '65028', 'High': '65326', 'Low': '64333', 'Close': '64333', 'Volume': '5627200', 'Value': '366683420000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '18/09/2025', 'Time': None, 'Open': '64433', 'High': '64433', 'Low': '63142', 'Close': '63440', 'Volume': '8783400', 'Value': '563070810000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '19/09/2025', 'Time': None, 'Open': '63738', 'High': '64036', 'Low': '62546', 'Close': '62546', 'Volume': '6932700', 'Value': '438861190000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '22/09/2025', 'Time': None, 'Open': '62546', 'High': '62745', 'Low': '61355', 'Close': '61554', 'Volume': '6061300', 'Value': '377811750000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '23/09/2025', 'Time': None, 'Open': '61951', 'High': '62646', 'Low': '61752', 'Close': '61752', 'Volume': '3267800', 'Value': '204691380000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '24/09/2025', 'Time': None, 'Open': '61951', 'High': '62249', 'Low': '61355', 'Close': '62249', 'Volume': '3879200', 'Value': '241048440000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '25/09/2025', 'Time': None, 'Open': '62844', 'High': '62944', 'Low': '62249', 'Close': '62546', 'Volume': '3870300', 'Value': '244105000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '26/09/2025', 'Time': None, 'Open': '62745', 'High': '62944', 'Low': '62447', 'Close': '62546', 'Volume': '3981900', 'Value': '251215760000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '29/09/2025', 'Time': None, 'Open': '62447', 'High': '62447', 'Low': '61951', 'Close': '62149', 'Volume': '2782900', 'Value': '174229910000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '30/09/2025', 'Time': None, 'Open': '62348', 'High': '62447', 'Low': '61355', 'Close': '61554', 'Volume': '4104100', 'Value': '255132620000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '01/10/2025', 'Time': None, 'Open': '62249', 'High': '62249', 'Low': '61554', 'Close': '61951', 'Volume': '3022000', 'Value': '188400460000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '02/10/2025', 'Time': None, 'Open': '61951', 'High': '62646', 'Low': '61653', 'Close': '61653', 'Volume': '3657500', 'Value': '229086420000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '03/10/2025', 'Time': None, 'Open': '62000', 'High': '62000', 'Low': '61400', 'Close': '61700', 'Volume': '2821100', 'Value': '174222830000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '06/10/2025', 'Time': None, 'Open': '62800', 'High': '64000', 'Low': '62800', 'Close': '64000', 'Volume': '7461700', 'Value': '474017050000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '07/10/2025', 'Time': None, 'Open': '64100', 'High': '64100', 'Low': '63300', 'Close': '63700', 'Volume': '4229300', 'Value': '269759710000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '08/10/2025', 'Time': None, 'Open': '64200', 'High': '64900', 'Low': '63600', 'Close': '64600', 'Volume': '8113800', 'Value': '520241720000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '09/10/2025', 'Time': None, 'Open': '64500', 'High': '65200', 'Low': '63800', 'Close': '63800', 'Volume': '5734200', 'Value': '368139750000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '10/10/2025', 'Time': None, 'Open': '63900', 'High': '64400', 'Low': '63600', 'Close': '64200', 'Volume': '4985600', 'Value': '319565470000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '13/10/2025', 'Time': None, 'Open': '63400', 'High': '63800', 'Low': '62800', 'Close': '63100', 'Volume': '7992500', 'Value': '505177750000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '14/10/2025', 'Time': None, 'Open': '63500', 'High': '64000', 'Low': '62900', 'Close': '63100', 'Volume': '7008900', 'Value': '443354140000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '15/10/2025', 'Time': None, 'Open': '63100', 'High': '63400', 'Low': '62500', 'Close': '62500', 'Volume': '5218800', 'Value': '329246580000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '16/10/2025', 'Time': None, 'Open': '62700', 'High': '63000', 'Low': '62500', 'Close': '62900', 'Volume': '4634400', 'Value': '290527390000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '17/10/2025', 'Time': None, 'Open': '62900', 'High': '62900', 'Low': '61800', 'Close': '61900', 'Volume': '5405900', 'Value': '336717510000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '20/10/2025', 'Time': None, 'Open': '61800', 'High': '62200', 'Low': '58600', 'Close': '59400', 'Volume': '12115600', 'Value': '740009000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '21/10/2025', 'Time': None, 'Open': '59700', 'High': '60700', 'Low': '59300', 'Close': '59300', 'Volume': '8416700', 'Value': '504612010000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '22/10/2025', 'Time': None, 'Open': '60100', 'High': '60200', 'Low': '58500', 'Close': '59600', 'Volume': '4664800', 'Value': '276154650000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '23/10/2025', 'Time': None, 'Open': '58900', 'High': '60300', 'Low': '58900', 'Close': '59800', 'Volume': '4227100', 'Value': '252653200000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '24/10/2025', 'Time': None, 'Open': '59800', 'High': '59900', 'Low': '58800', 'Close': '59500', 'Volume': '4372700', 'Value': '260109200000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '27/10/2025', 'Time': None, 'Open': '60000', 'High': '60000', 'Low': '59200', 'Close': '59200', 'Volume': '2640000', 'Value': '157145230000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '28/10/2025', 'Time': None, 'Open': '59200', 'High': '60200', 'Low': '59100', 'Close': '60000', 'Volume': '2789700', 'Value': '166577550000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '29/10/2025', 'Time': None, 'Open': '60000', 'High': '61000', 'Low': '59800', 'Close': '60700', 'Volume': '3716000', 'Value': '223920940000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '30/10/2025', 'Time': None, 'Open': '61000', 'High': '61200', 'Low': '60300', 'Close': '60600', 'Volume': '1946600', 'Value': '118304140000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '31/10/2025', 'Time': None, 'Open': '60800', 'High': '60800', 'Low': '59600', 'Close': '59600', 'Volume': '2117800', 'Value': '127319000000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '03/11/2025', 'Time': None, 'Open': '60000', 'High': '60300', 'Low': '59300', 'Close': '59300', 'Volume': '2800100', 'Value': '167153680000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '04/11/2025', 'Time': None, 'Open': '59200', 'High': '60400', 'Low': '59100', 'Close': '60100', 'Volume': '2952400', 'Value': '176177680000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '05/11/2025', 'Time': None, 'Open': '60000', 'High': '61100', 'Low': '59900', 'Close': '60800', 'Volume': '4601700', 'Value': '278521160000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '06/11/2025', 'Time': None, 'Open': '60900', 'High': '61300', 'Low': '60200', 'Close': '60300', 'Volume': '2821200', 'Value': '171095140000'}, {'Symbol': 'VCB', 'Market': 'HOSE', 'TradingDate': '07/11/2025', 'Time': None, 'Open': '60000', 'High': '60000', 'Low': '59000', 'Close': '59300', 'Volume': '3586300', 'Value': '213567960000'}], 'message': 'Success', 'status': 'Success', 'totalRecord': 69}

In [10]:
data

      Datetime   Open   High    Low  Close    Volume
0   01/08/2025  59866  60164  59270  59767   4751600
1   04/08/2025  59667  60958  59568  60660   4462400
2   05/08/2025  61057  63241  60759  61057  18590000
3   06/08/2025  61653  62348  61454  61851   4677500
4   07/08/2025  62447  62447  60859  61256   9498700
..         ...    ...    ...    ...    ...       ...
64  03/11/2025  60000  60300  59300  59300   2800100
65  04/11/2025  59200  60400  59100  60100   2952400
66  05/11/2025  60000  61100  59900  60800   4601700
67  06/11/2025  60900  61300  60200  60300   2821200
68  07/11/2025  60000  60000  59000  59300   3586300

[69 rows x 6 columns]

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  69 non-null     object
 1   Open      69 non-null     object
 2   High      69 non-null     object
 3   Low       69 non-null     object
 4   Close     69 non-null     object
 5   Volume    69 non-null     object
dtypes: object(6)
memory usage: 3.4+ KB

# Chuyen doi kieu du lieu

In [15]:
import pandas as pd
# data['Date'] = pd.to_datetime(data['Datetime'])
data['Close'] = pd.to_numeric(data['Close'], errors='coerce')
data['Open'] = pd.to_numeric(data['Open'], errors='coerce')
data['High'] = pd.to_numeric(data['High'], errors='coerce')
data['Low'] = pd.to_numeric(data['Low'], errors='coerce')
data['Volume'] = pd.to_numeric(data['Volume'], errors='coerce')	
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  69 non-null     object
 1   Open      69 non-null     int64
 2   High      69 non-null     int64
 3   Low       69 non-null     int64
 4   Close     69 non-null     int64
 5   Volume    69 non-null     int64
dtypes: int64(5), object(1)
memory usage: 3.4+ KB

In [16]:
# Import các thư viện cần thiết
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [17]:
import numpy as np
from itertools import combinations

basic_features = ['Open', 'High', 'Low', 'Volume', 'Momentum', 'RSI'] # 6 bien doc lap

# Tạo tất cả tổ hợp có thể từ basic_features
# Sử dụng itertools để tạo tất cả các tổ hợp của các đặc trưng
features_combinations = []
for r in range(1, len(basic_features) + 1):
    for combo in combinations(basic_features, r):
        features_combinations.append(list(combo))

print(features_combinations)
print(len(features_combinations))

[['Open'], ['High'], ['Low'], ['Volume'], ['Momentum'], ['RSI'], ['Open', 'High'], ['Open', 'Low'], ['Open', 'Volume'], ['Open', 'Momentum'], ['Open', 'RSI'], ['High', 'Low'], ['High', 'Volume'], ['High', 'Momentum'], ['High', 'RSI'], ['Low', 'Volume'], ['Low', 'Momentum'], ['Low', 'RSI'], ['Volume', 'Momentum'], ['Volume', 'RSI'], ['Momentum', 'RSI'], ['Open', 'High', 'Low'], ['Open', 'High', 'Volume'], ['Open', 'High', 'Momentum'], ['Open', 'High', 'RSI'], ['Open', 'Low', 'Volume'], ['Open', 'Low', 'Momentum'], ['Open', 'Low', 'RSI'], ['Open', 'Volume', 'Momentum'], ['Open', 'Volume', 'RSI'], ['Open', 'Momentum', 'RSI'], ['High', 'Low', 'Volume'], ['High', 'Low', 'Momentum'], ['High', 'Low', 'RSI'], ['High', 'Volume', 'Momentum'], ['High', 'Volume', 'RSI'], ['High', 'Momentum', 'RSI'], ['Low', 'Volume', 'Momentum'], ['Low', 'Volume', 'RSI'], ['Low', 'Momentum', 'RSI'], ['Volume', 'Momentum', 'RSI'], ['Open', 'High', 'Low', 'Volume'], ['Open', 'High', 'Low', 'Momentum'], ['Open', 'High', 'Low', 'RSI'], ['Open', 'High', 'Volume', 'Momentum'], ['Open', 'High', 'Volume', 'RSI'], ['Open', 'High', 'Momentum', 'RSI'], ['Open', 'Low', 'Volume', 'Momentum'], ['Open', 'Low', 'Volume', 'RSI'], ['Open', 'Low', 'Momentum', 'RSI'], ['Open', 'Volume', 'Momentum', 'RSI'], ['High', 'Low', 'Volume', 'Momentum'], ['High', 'Low', 'Volume', 'RSI'], ['High', 'Low', 'Momentum', 'RSI'], ['High', 'Volume', 'Momentum', 'RSI'], ['Low', 'Volume', 'Momentum', 'RSI'], ['Open', 'High', 'Low', 'Volume', 'Momentum'], ['Open', 'High', 'Low', 'Volume', 'RSI'], ['Open', 'High', 'Low', 'Momentum', 'RSI'], ['Open', 'High', 'Volume', 'Momentum', 'RSI'], ['Open', 'Low', 'Volume', 'Momentum', 'RSI'], ['High', 'Low', 'Volume', 'Momentum', 'RSI'], ['Open', 'High', 'Low', 'Volume', 'Momentum', 'RSI']]
63

# To hop cac bien doc lap X

In [18]:
data

      Datetime   Open   High    Low  Close    Volume
0   01/08/2025  59866  60164  59270  59767   4751600
1   04/08/2025  59667  60958  59568  60660   4462400
2   05/08/2025  61057  63241  60759  61057  18590000
3   06/08/2025  61653  62348  61454  61851   4677500
4   07/08/2025  62447  62447  60859  61256   9498700
..         ...    ...    ...    ...    ...       ...
64  03/11/2025  60000  60300  59300  59300   2800100
65  04/11/2025  59200  60400  59100  60100   2952400
66  05/11/2025  60000  61100  59900  60800   4601700
67  06/11/2025  60900  61300  60200  60300   2821200
68  07/11/2025  60000  60000  59000  59300   3586300

[69 rows x 6 columns]

In [21]:
import numpy as np
from itertools import combinations
import talib

# Đảm bảo cột 'Datetime' được hiểu là kiểu dữ liệu datetime và đã sắp xếp
# data['Datetime'] = pd.to_datetime(data['Datetime'])
# data.sort_values(by='Datetime', inplace=True)

# Drop cột 'Datetime'
data.drop(columns=['Datetime'], inplace=True)

# Thêm Momentum và RSI vào DataFrame
data['Momentum'] = talib.MOM(data['Close'], timeperiod=14)
data['RSI'] = talib.RSI(data['Close'], timeperiod=14)

# Loại bỏ NaN
# data.dropna(inplace=True)

data.fillna(data.mean(), inplace=True) # Thay thế NaN bằng giá trị trung bình của cột

# Định nghĩa cơ bản của các đặc trưng
# 'Open', 'High', 'Low', 'Volume', 'Momentum', 'RSI'
basic_features = ['Open', 'High', 'Low', 'Volume', 'Momentum', 'RSI']

# Khởi tạo biến mục tiêu 'y' là giá đóng cửa
y = data['Close']

# Tạo tất cả tổ hợp có thể từ basic_features
# Sử dụng itertools để tạo tất cả các tổ hợp của các đặc trưng
features_combinations = []
for r in range(1, len(basic_features) + 1):
    for combo in combinations(basic_features, r):
        features_combinations.append(list(combo))

# Luu trữ kết quả MSE cho từng tổ hợp
mse_scores = {} # Dictionary luu trữ MSE cho từng tổ hợp

# Kiểm tra từng kết hợp đặc trưng
for features in features_combinations:
    X = data[features].copy() # Copy dữ liệu để tránh thay đổi gốc
	# Thay thế NaN bằng giá trị trung bình của cột
    X.fillna(X.mean(), inplace=True)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    model = DecisionTreeRegressor(random_state=42)
    model.fit(X_train, y_train)
    
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions) # Tinh MSE
    
    mse_scores[str(features)] = mse # Them vao dictionary mse_scores

print(mse_scores)
# Tìm kết hợp đặc trưng với MSE thấp nhất
best_features = min(mse_scores, key=mse_scores.get)
print(f"Best features: {best_features} with MSE: {mse_scores[best_features]}")

{"['Open']": 3793155.1428571427, "['High']": 939029.9642857143, "['Low']": 1745194.984126984, "['Volume']": 6450485.214285715, "['Momentum']": 3164719.8928571427, "['RSI']": 3175486.5535714286, "['Open', 'High']": 1083293.5, "['Open', 'Low']": 1920300.357142857, "['Open', 'Volume']": 5002796.428571428, "['Open', 'Momentum']": 2604203.5178571427, "['Open', 'RSI']": 3662858.589285714, "['High', 'Low']": 1158794.4285714286, "['High', 'Volume']": 1012357.8571428572, "['High', 'Momentum']": 1030141.1428571428, "['High', 'RSI']": 899572.0, "['Low', 'Volume']": 1910471.7857142857, "['Low', 'Momentum']": 1964468.9285714286, "['Low', 'RSI']": 1403114.7142857143, "['Volume', 'Momentum']": 3817434.214285714, "['Volume', 'RSI']": 4571706.142857143, "['Momentum', 'RSI']": 1586478.0357142857, "['Open', 'High', 'Low']": 928009.7857142857, "['Open', 'High', 'Volume']": 1197726.5, "['Open', 'High', 'Momentum']": 495435.5, "['Open', 'High', 'RSI']": 597273.4285714285, "['Open', 'Low', 'Volume']": 1882657.4285714286, "['Open', 'Low', 'Momentum']": 2764924.9285714286, "['Open', 'Low', 'RSI']": 2314110.0714285714, "['Open', 'Volume', 'Momentum']": 3857318.5, "['Open', 'Volume', 'RSI']": 3394421.714285714, "['Open', 'Momentum', 'RSI']": 4955565.803571428, "['High', 'Low', 'Volume']": 1178955.0, "['High', 'Low', 'Momentum']": 1120521.142857143, "['High', 'Low', 'RSI']": 931441.9285714285, "['High', 'Volume', 'Momentum']": 1058175.7142857143, "['High', 'Volume', 'RSI']": 943823.5714285715, "['High', 'Momentum', 'RSI']": 273126.21428571426, "['Low', 'Volume', 'Momentum']": 1590021.2142857143, "['Low', 'Volume', 'RSI']": 1434809.7857142857, "['Low', 'Momentum', 'RSI']": 1404438.7142857143, "['Volume', 'Momentum', 'RSI']": 2853119.6428571427, "['Open', 'High', 'Low', 'Volume']": 2561206.3571428573, "['Open', 'High', 'Low', 'Momentum']": 2109088.0, "['Open', 'High', 'Low', 'RSI']": 846956.4285714285, "['Open', 'High', 'Volume', 'Momentum']": 2675091.0, "['Open', 'High', 'Volume', 'RSI']": 2946497.5, "['Open', 'High', 'Momentum', 'RSI']": 2627395.1428571427, "['Open', 'Low', 'Volume', 'Momentum']": 2865892.5714285714, "['Open', 'Low', 'Volume', 'RSI']": 2576541.785714286, "['Open', 'Low', 'Momentum', 'RSI']": 2556566.0, "['Open', 'Volume', 'Momentum', 'RSI']": 3640684.214285714, "['High', 'Low', 'Volume', 'Momentum']": 1481103.357142857, "['High', 'Low', 'Volume', 'RSI']": 569454.9285714285, "['High', 'Low', 'Momentum', 'RSI']": 525252.8571428572, "['High', 'Volume', 'Momentum', 'RSI']": 419275.9285714286, "['Low', 'Volume', 'Momentum', 'RSI']": 1586943.642857143, "['Open', 'High', 'Low', 'Volume', 'Momentum']": 1985036.2142857143, "['Open', 'High', 'Low', 'Volume', 'RSI']": 520618.78571428574, "['Open', 'High', 'Low', 'Momentum', 'RSI']": 496261.35714285716, "['Open', 'High', 'Volume', 'Momentum', 'RSI']": 2978598.8571428573, "['Open', 'Low', 'Volume', 'Momentum', 'RSI']": 2471109.0, "['High', 'Low', 'Volume', 'Momentum', 'RSI']": 1747948.5714285714, "['Open', 'High', 'Low', 'Volume', 'Momentum', 'RSI']": 1530247.5}
Best features: ['High', 'Momentum', 'RSI'] with MSE: 273126.21428571426

# Moi lan chay la so sanh

In [22]:
# Dat MSE la gia tri vo cuc
best_mse = float('inf')
best_features = None

for features in features_combinations:
    X = data[features].copy()
    X.fillna(X.mean(), inplace=True)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    model = DecisionTreeRegressor(random_state=42)
    model.fit(X_train, y_train)
    
    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    
    # Kiểm tra xem MSE của lần lặp này có nhỏ hơn giá trị tốt nhất hiện tại không
    if mse < best_mse:
        best_mse = mse
        best_features = features

print(f"Best features: {best_features} with MSE: {best_mse}")

Best features: ['High', 'Momentum', 'RSI'] with MSE: 273126.21428571426