# Bai tap
Crypto BTCUSDT
- Chien luoc mua xay ra khi: MA10 nam tren MA20
- Chien luoc ban xay ra khi: MA10 nam duoc MA20

# Load data len

#### Ham lay du lieu

In [1]:
def loaddataBinance_FromTo(symbol, from_date, to_date, timeframe):
    import pandas as pd
    import ccxt
    from datetime import datetime, timedelta

    # Khởi tạo kết nối đến sàn Binance
    exchange = ccxt.binance()

    # Định dạng ngày tháng
    since = exchange.parse8601(from_date + 'T00:00:00Z')
    end = exchange.parse8601(to_date + 'T00:00:00Z')

    # Lấy dữ liệu thị trường từ sàn Binance
    # 1d
    ohlcv = exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=1000)

    # Chuyển dữ liệu thành DataFrame
    data = pd.DataFrame(ohlcv, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
    data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='ms')         
    data = data.rename(columns={'Timestamp': 'Datetime'})

    return data

In [2]:
from datetime import datetime, timedelta
# ##############################################Step 0: Các tham số để lấy dữ liệu###############################
symbol = 'BTCUSDT'
from_date = (datetime.now() - timedelta(days=0)).strftime('%Y-%m-%d')  # Lấy ngày hôm qua
to_date = (datetime.now() + timedelta(days=0)).strftime('%Y-%m-%d')
timeframe = '1m' # 1m

# ##############################################Step 1: Lấy dữ liệu##############################################
data = loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)
data

               Datetime      Open      High       Low     Close     Volume
0   2024-11-15 00:00:00  87325.59  87374.99  87252.00  87374.99   48.11170
1   2024-11-15 00:01:00  87374.99  87650.00  87353.18  87620.01  116.50616
2   2024-11-15 00:02:00  87620.00  87684.00  87456.00  87556.00   60.67595
3   2024-11-15 00:03:00  87556.00  87678.90  87521.23  87580.01   41.96184
4   2024-11-15 00:04:00  87580.01  87712.00  87580.00  87687.99   39.40457
..                  ...       ...       ...       ...       ...        ...
825 2024-11-15 13:45:00  89941.77  90084.82  89925.28  89971.38  114.19513
826 2024-11-15 13:46:00  89971.38  90183.95  89971.38  90183.94   40.03952
827 2024-11-15 13:47:00  90183.94  90212.13  90164.20  90193.43   33.66510
828 2024-11-15 13:48:00  90193.43  90193.43  90089.94  90175.98   51.54623
829 2024-11-15 13:49:00  90175.98  90200.00  90156.59  90167.55    6.90010

[830 rows x 6 columns]

# Tinh toan them chi bao MA10, MA20

In [3]:
import talib
data['MA10'] = talib.SMA(data['Close'], timeperiod=10)
data['MA20'] = talib.SMA(data['Close'], timeperiod=20)
data

,Datetime,Open,High,Low,Close,Volume,MA10,MA20
0,2024-11-15 00:00:00,87325.59,87374.99,87252.00,87374.99,48.11170,NaN,NaN
1,2024-11-15 00:01:00,87374.99,87650.00,87353.18,87620.01,116.50616,NaN,NaN
2,2024-11-15 00:02:00,87620.00,87684.00,87456.00,87556.00,60.67595,NaN,NaN
3,2024-11-15 00:03:00,87556.00,87678.90,87521.23,87580.01,41.96184,NaN,NaN
4,2024-11-15 00:04:00,87580.01,87712.00,87580.00,87687.99,39.40457,NaN,NaN
...,...,...,...,...,...,...,...,...
825,2024-11-15 13:45:00,89941.77,90084.82,89925.28,89971.38,114.19513,89702.947,89698.8465
826,2024-11-15 13:46:00,89971.38,90183.95,89971.38,90183.94,40.03952,89778.500,89726.9920
827,2024-11-15 13:47:00,90183.94,90212.13,90164.20,90193.43,33.66510,89849.842,89755.4630
828,2024-11-15 13:48:00,90193.43,90193.43,90089.94,90175.98,51.54623,89918.038,89782.0520
829,2024-11-15 13:49:00,90175.98,90200.00,90156.59,90167.55,6.90010,89978.812,89810.4365

In [4]:
data.to_csv('Buoi 5.Bai tap tai lop 1.csv')

# Tinh Buy_Signal, Sell_Signal

In [6]:
data['Buy_Signal'] = (data['MA10'] > data['MA20'])
data['Sell_Signal'] = (data['MA10'] < data['MA20'])
data

,Datetime,Open,High,Low,Close,Volume,MA10,MA20,Buy_Signal,Sell_Signal
0,2024-11-15 00:00:00,87325.59,87374.99,87252.00,87374.99,48.11170,NaN,NaN,False,False
1,2024-11-15 00:01:00,87374.99,87650.00,87353.18,87620.01,116.50616,NaN,NaN,False,False
2,2024-11-15 00:02:00,87620.00,87684.00,87456.00,87556.00,60.67595,NaN,NaN,False,False
3,2024-11-15 00:03:00,87556.00,87678.90,87521.23,87580.01,41.96184,NaN,NaN,False,False
4,2024-11-15 00:04:00,87580.01,87712.00,87580.00,87687.99,39.40457,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...
825,2024-11-15 13:45:00,89941.77,90084.82,89925.28,89971.38,114.19513,89702.947,89698.8465,True,False
826,2024-11-15 13:46:00,89971.38,90183.95,89971.38,90183.94,40.03952,89778.500,89726.9920,True,False
827,2024-11-15 13:47:00,90183.94,90212.13,90164.20,90193.43,33.66510,89849.842,89755.4630,True,False
828,2024-11-15 13:48:00,90193.43,90193.43,90089.94,90175.98,51.54623,89918.038,89782.0520,True,False
829,2024-11-15 13:49:00,90175.98,90200.00,90156.59,90167.55,6.90010,89978.812,89810.4365,True,False