# Lay du lieu yfinance

In [1]:
import yfinance as yf
ticker = "VCB.VN" # Symbol

In [4]:
import yfinance as yf
ticker = "VCB.VN" # Symbol

data = yf.download(ticker, start="2025-09-01", end="2025-09-20", interval='1d')

data

[*********************100%***********************]  1 of 1 completed

Price         Close     High      Low     Open    Volume
Ticker       VCB.VN   VCB.VN   VCB.VN   VCB.VN    VCB.VN
Date
2025-09-03  67000.0  68800.0  67000.0  68800.0  14579980
2025-09-04  68900.0  69000.0  66900.0  67500.0   9042641
2025-09-05  67500.0  69600.0  67500.0  69500.0  11260080
2025-09-08  65300.0  67500.0  65300.0  67100.0  11211920
2025-09-09  64900.0  66200.0  64500.0  65500.0   6448308
2025-09-10  65800.0  66000.0  64800.0  65600.0   5013842
2025-09-11  65700.0  66000.0  64200.0  65600.0   6639770
2025-09-12  65800.0  66200.0  65000.0  66200.0   5700154
2025-09-15  65800.0  66000.0  65500.0  66000.0  12025590
2025-09-16  65600.0  66600.0  65600.0  66000.0   6829896
2025-09-17  64800.0  65800.0  64800.0  65500.0   6275957
2025-09-18  63900.0  64900.0  63600.0  64900.0   8815058
2025-09-19  63000.0  64500.0  63000.0  64200.0   7148361

In [13]:
import yfinance as yf

# Define the ticker symbol
ticker_symbol = 'VCB.VN'

# Get data on this ticker
ticker_data = yf.Ticker(ticker_symbol)

# Get the historical prices for this ticker
ticker_df = ticker_data.history(period='1mo', interval='1m', start='2025-09-15', end='2025-09-20')

# Display the data
# ticker_df.head()
ticker_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-09-15 09:15:00+07:00,66000.0,66000.0,65900.0,66000.0,0,0.0,0.0
2025-09-15 09:16:00+07:00,65900.0,65900.0,65800.0,65800.0,36601,0.0,0.0
2025-09-15 09:17:00+07:00,65900.0,65900.0,65800.0,65800.0,54405,0.0,0.0
2025-09-15 09:18:00+07:00,65800.0,65900.0,65800.0,65900.0,15200,0.0,0.0
2025-09-15 09:19:00+07:00,65900.0,66000.0,65900.0,66000.0,18710,0.0,0.0
...,...,...,...,...,...,...,...
2025-09-19 14:26:00+07:00,63200.0,63300.0,63200.0,63200.0,49210,0.0,0.0
2025-09-19 14:27:00+07:00,63200.0,63300.0,63200.0,63300.0,26700,0.0,0.0
2025-09-19 14:28:00+07:00,63200.0,63300.0,63200.0,63300.0,51303,0.0,0.0
2025-09-19 14:29:00+07:00,63300.0,63300.0,63200.0,63300.0,65719,0.0,0.0
2025-09-19 14:45:00+07:00,63000.0,63000.0,63000.0,63000.0,2079701,0.0,0.0

# Bai tap: Viet ham de lay du lieu cua ma chung khoan ACB tren Yfinance trong vong 10 ngay, voi interval = 5m

In [15]:
import yfinance as yf
def getDataYFinance(ticker, start, end, interval='5m'):
	"""
	Fetch historical data for a given ticker symbol from Yahoo Finance.
	
	Parameters:
	ticker (str): The ticker symbol to fetch data for.
	start (str): The start date in 'YYYY-MM-DD' format.
	end (str): The end date in 'YYYY-MM-DD' format.
	interval (str): The data interval (default is '5m').
	
	Returns:
	DataFrame: A pandas DataFrame containing the historical data.
	"""
	return yf.download(ticker, start=start, end=end, interval=interval)	

# Goi ham
data = getDataYFinance('AAPL', '2025-09-01', '2025-09-25', interval='5m')
data

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
Datetime,,,,,
2025-09-02 13:30:00+00:00,228.154999,228.779999,227.690002,228.750000,3169842
2025-09-02 13:35:00+00:00,229.279999,229.490005,228.014999,228.139999,1170465
2025-09-02 13:40:00+00:00,229.389999,229.529999,228.770004,229.289993,677010
2025-09-02 13:45:00+00:00,229.378998,229.869995,229.000000,229.369995,649580
2025-09-02 13:50:00+00:00,230.289993,230.309998,229.300003,229.373199,648222
...,...,...,...,...,...
2025-09-19 14:20:00+00:00,240.839996,241.089996,240.449997,240.550003,686856
2025-09-19 14:25:00+00:00,241.149994,241.240005,240.789993,240.859894,641270
2025-09-19 14:30:00+00:00,241.695007,241.710007,241.059998,241.149994,700172
2025-09-19 14:35:00+00:00,241.710007,241.830002,241.410004,241.699203,657640
2025-09-19 14:40:00+00:00,242.000000,242.080002,241.479996,241.710007,952184