# Co 2 thu vien: ccxt, binance

In [1]:
# Xai ccxt
# Dung ccxt de lay du lieu tu Binance
import ccxt
import pandas as pd
from datetime import datetime

# Khởi tạo exchange Binance
exchange = ccxt.binance() # ccxt co the ket noi den hon 150 san Crypto toan the gioi

# Lấy dữ liệu OHLCV (Open, High, Low, Close, Volume)
symbol = 'BTC/USDT'  # Cặp tiền
timeframe = '1h'     # Khung thời gian: 1m, 5m, 15m, 1h, 4h, 1d, 1w, 1M

# Lấy 100 nến gần nhất
ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=100)

# Chuyển thành DataFrame
df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])

# Chuyển timestamp thành datetime
df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms') # Timestamp dang miligiay
df.set_index('datetime', inplace=True)

print(df.tail())

                         timestamp       open       high        low  \
datetime
2025-09-22 05:00:00  1758517200000  114433.53  114551.80  113623.00
2025-09-22 06:00:00  1758520800000  113691.18  113698.38  111800.00
2025-09-22 07:00:00  1758524400000  112800.77  112999.00  112476.17
2025-09-22 08:00:00  1758528000000  112520.00  112780.00  112452.00
2025-09-22 09:00:00  1758531600000  112629.06  112662.87  112199.55

                         close      volume
datetime
2025-09-22 05:00:00  113691.19   753.79586
2025-09-22 06:00:00  112800.77  5199.12797
2025-09-22 07:00:00  112519.99  1129.86840
2025-09-22 08:00:00  112629.07   810.01414
2025-09-22 09:00:00  112288.10   861.75389

In [ ]:
def getData_Binance(symbol, timeframe, limit=100):
	# Xai ccxt
	# Dung ccxt de lay du lieu tu Binance
	import ccxt
	import pandas as pd
	from datetime import datetime

	# Khởi tạo exchange Binance
	exchange = ccxt.binance() # ccxt co the ket noi den hon 150 san Crypto toan the gioi

	# Lấy dữ liệu OHLCV (Open, High, Low, Close, Volume)
	symbol = 'BTC/USDT'  # Cặp tiền
	timeframe = '1h'     # Khung thời gian: 1m, 5m, 15m, 1h, 4h, 1d, 1w, 1M

	# Lấy 100 nến gần nhất
	ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=100)

	# Chuyển thành DataFrame
	df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])

	# Chuyển timestamp thành datetime
	df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms') # Timestamp dang miligiay
	df.set_index('datetime', inplace=True)

	return df

# Goi ham truc tiep o tren

In [ ]:
# Goi ham truc tiep o tren
data = getData_Binance("BTC/USDT", "1h", 100)
data

# Goi ham trong Common

In [ ]:
import sys 
sys.path.append("../Common")

import TradeBinance

data = TradeBinance.TradeBinance.getData_Binance("BTC/USDT", "1h", 100)
data

In [9]:
import sys 
sys.path.append("../Common")

from TradeBinance import TradeBinance

data = TradeBinance.getData_Binance("BTC/USDT", "1h", 100)
data

,timestamp,open,high,low,close,volume
datetime,,,,,,
2025-09-15 12:00:00,1757937600000,115070.01,115074.51,114671.75,114721.04,599.02223
2025-09-15 13:00:00,1757941200000,114721.03,115099.00,114384.00,114664.08,1056.42151
2025-09-15 14:00:00,1757944800000,114664.07,115029.81,114450.28,114679.56,775.27929
2025-09-15 15:00:00,1757948400000,114679.55,114909.40,114404.43,114842.90,564.69333
2025-09-15 16:00:00,1757952000000,114842.90,114922.59,114600.00,114662.57,364.30154
...,...,...,...,...,...,...
2025-09-19 11:00:00,1758279600000,116532.68,116554.05,116300.00,116394.72,309.23241
2025-09-19 12:00:00,1758283200000,116394.72,116529.08,116133.66,116162.45,488.73837
2025-09-19 13:00:00,1758286800000,116162.45,116465.35,116075.00,116284.64,435.12378
2025-09-19 14:00:00,1758290400000,116284.63,116479.11,115800.00,115899.99,846.39402
2025-09-19 15:00:00,1758294000000,115899.99,115900.00,115488.49,115536.22,370.20321

In [13]:
import sys 
sys.path.append("../Common")

import MetaTrader5 as mt5
from TradeMT5 import TradeMT5

data = TradeMT5.getData_MT5("US30", mt5.TIMEFRAME_M1, 1)
data

,Open,High,Low,Close,Volume,spread,real_volume
time,,,,,,,
2025-09-19 18:23:00,46197.0,46197.0,46188.5,46196.5,42,15,0

# Coinbase

In [ ]:
# Xai ccxt
# Dung ccxt de lay du lieu tu Binance
import ccxt
import pandas as pd
from datetime import datetime

# Khởi tạo exchange Binance
exchange = ccxt.coinbase() # ccxt co the ket noi den hon 150 san Crypto toan the gioi

# Lấy dữ liệu OHLCV (Open, High, Low, Close, Volume)
symbol = 'BTC/USDT'  # Cặp tiền
timeframe = '1h'     # Khung thời gian: 1m, 5m, 15m, 1h, 4h, 1d, 1w, 1M

# Lấy 100 nến gần nhất
ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=100)

# Chuyển thành DataFrame
df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])

# Chuyển timestamp thành datetime
df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms') # Timestamp dang miligiay
df.set_index('datetime', inplace=True)

print(df.tail())

# Lay volume them gio, theo ngay cua 10 san lon nhat
# So sanh volume cua thang dung thu 1 voi 9 thang con lai