# Vi du ve Input

In [1]:
print('Moi ban nhap cai gi do') # Yeu cau => In ra man hinh
sos = input('Nhap vao so nguyen: ') # Input la ham nhap du lieu tu ban phim, gan cho bien sos
print('Ban da nhap: ', sos)
print('Ban da nhap kieu du lieu ', type(sos)) # Kiem tra kieu du lieu cua bien sos

Moi ban nhap cai gi do
Ban da nhap:  123
Ban da nhap kieu du lieu  <class 'str'>

# Ep kieu

In [2]:
sos = int(sos) # Chuyen doi kieu du lieu tu string sang float = Ep kieu du lieu
print('Ban da nhap kieu du lieu ', type(sos))

Ban da nhap kieu du lieu  <class 'int'>

In [3]:
sos = float(sos) # Chuyen doi kieu du lieu tu string sang float

# Ham output

In [ ]:
print('sos') # In ra chuoi 'sos' thay vi bien sos
print(sos) # In ra bien sos, khong can dau ngoac don vi

sos
123.0

# Ham format

In [ ]:
s = input('Moi ban nhap vao: ') # Input la ham nhap du lieu tu ban phim, gan cho bien s

print('{0} la {1} --- {2}'.format(s, type(s), 4)) # In ra kieu du lieu cua bien s

3 la <class 'str'> --- 4

In [8]:
print('{0} {2} {1}'.format('s', 'type(s)', 'Thu 3'))

s Thu 3 type(s)

In [10]:
a = 1
b = 2
c = 3

print('Gia tri cua a la: {0}, b la: {1}, a la: {0}'.format(a, b, c)) # In ra gia tri cua a, b, c

Gia tri cua a la: 1, b la: 2, a la: 1

# Check loi

In [ ]:
x = 2
y = - x
# Gia su chuyen ve
y + x = 0
y = -x

# Bat loi

In [14]:
x = 0
y = 1/x # Co loi nen ko chay tiep nua

ZeroDivisionError: division by zero

In [15]:
try:
	x = 0
	y = 1/x # Chay quan doan lenh nay
except: # Neu co loi xay ra thi chay lenh nay, nem loi ra e - e nay chung ta thay bang gi cung duoc
	print("Loi")

Loi

# Bat loi bang try except

In [16]:
try: # Bat loi bang try except
	x = 0
	y = 1/x # Chay quan doan lenh nay
except Exception as ee: # Neu co loi xay ra thi chay lenh nay, nem loi ra e - e nay chung ta thay bang gi cung duoc
	print(ee)

division by zero

# Nhap 1 gia tri bat ky tu ban phim
### Chuyen gia tri do sang float
### Neu chuyen khong duoc thi in ra loi

In [18]:
x = input("Nhập vào dữ liêu: ")
try:
	x =float(x)
	print(x)
except:
	print("Lỗi")

1.0

In [ ]:
x = input("Nhập vào dữ liêu: ")
while True:
    try:
        x =float(x)
        print(x)
        break
    except:
        print("Lỗi")
        x = input("Nhập lại: ")

# Nhap 1 gia tri bat ky tu ban phim
### Chuyen gia tri do sang float
### Neu chuyen khong duoc thi in ra loi va yeu cau nhap lai cho den khi khong co loi

# Bai tap: Nhap vao ban kinh r, tinh chu vi va dien tich cua duong tron

In [19]:
import math
r = input("Nhập vào bán kính r: ")
try:
	r = float(r)
	chu_vi = 2 * math.pi * r
	dien_tich = math.pi * r**2

	print("Chu vi của đường tròn là: ", chu_vi)
	print(f"Chu vi của đường tròn là: {chu_vi}")
	
	print("Diện tích của đường tròn là: ", dien_tich)
	print(f"Diện tích của đường tròn là: {dien_tich}")
	
except:
	print("Lỗi")
	# r = input("Nhập lại: ")

Chu vi của đường tròn là:  6.283185307179586
Chu vi của đường tròn là: 6.283185307179586
Diện tích của đường tròn là:  3.141592653589793
Diện tích của đường tròn là: 3.141592653589793

# Ham

In [ ]:
# Ham cong 2 so
def cong2so(a, b): 
	ketqua = a + b

	return ketqua

In [22]:
ketquaham = cong2so(1, 2)
print(ketquaham)

3

In [24]:
ketquaham = cong2so(1, 10)
print(ketquaham)

11

# Nhap vao ban kinh r, tinh chu vi va dien tich duong tron
# Viet ham tinh va in ra

In [25]:
# Nhap vao ban kinh r, tinh chu vi va dien tich duong tron
# Viet ham tinh va in ra

# Ham tinh chu vi va dien tich duong tron
def tinh_chu_vi(r):
	chu_vi = 2 * math.pi * r
	return chu_vi

def tinh_dien_tich(r):
	dien_tich = math.pi * r**2
	return dien_tich

r = input("Nhập vào bán kính r: ")
try:
	r = float(r)
	chu_vi = tinh_chu_vi(r)
	print(f"Chu vi của đường tròn là: {chu_vi}")
	dien_tich = tinh_dien_tich(r)
	print(f"Diện tích của đường tròn là: {dien_tich}")
	
except:
	print("Lỗi")

Chu vi của đường tròn là: 6.283185307179586
Diện tích của đường tròn là: 3.141592653589793

# Bai tap: Viet ham lay du lieu gia BTC tu Binance

In [36]:
import ccxt
binance = ccxt.binance()

# Lay du lieu gia BTC tu Binance
def lay_gia_btc(symbol):
    try:
        ticker = binance.fetch_ticker(f'{symbol.upper()}/USDT')
        return ticker
    except Exception as e:
        print(f"Lỗi: {e}")
        return None

In [ ]:
def loaddataBinance_FromTo(symbol, from_date, to_date, timeframe):
    import pandas as pd
    import ccxt
    from datetime import datetime

    # Khởi tạo kết nối đến sàn Binance
    exchange = ccxt.binance()

    # Định dạng ngày tháng
    since = exchange.parse8601(from_date + 'T00:00:00Z')
    end = exchange.parse8601(to_date + 'T00:00:00Z')

    # Lấy dữ liệu thị trường từ sàn Binance
    # 1d
    ohlcv = exchange.fetch_ohlcv(symbol, timeframe=timeframe, since=since, limit=1000)

    # Chuyển dữ liệu thành DataFrame
    data = pd.DataFrame(ohlcv, columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
    data['Timestamp'] = pd.to_datetime(data['Timestamp'], unit='ms')         
    data = data.rename(columns={'Timestamp': 'Datetime'})

    return data

In [43]:
symbol = input("Nhập vào symbol: ")

ticker = lay_gia_btc(symbol)

print("Gia cua", symbol, "la:", ticker)
print(f"Gia cua {symbol} la: {ticker}")

Gia cua btc la: {'symbol': 'BTC/USDT', 'timestamp': 1758123945013, 'datetime': '2025-09-17T15:45:45.013Z', 'high': 117286.73, 'low': 115408.0, 'bid': 115852.97, 'bidVolume': 2.0794, 'ask': 115852.98, 'askVolume': 4.56733, 'vwap': 116488.26463325, 'open': 115412.5, 'close': 115852.98, 'last': 115852.98, 'previousClose': 115412.51, 'change': 440.48, 'percentage': 0.382, 'average': 115632.74, 'baseVolume': 13019.4855, 'quoteVolume': 1516617272.3127382, 'markPrice': None, 'indexPrice': None, 'info': {'symbol': 'BTCUSDT', 'priceChange': '440.48000000', 'priceChangePercent': '0.382', 'weightedAvgPrice': '116488.26463325', 'prevClosePrice': '115412.51000000', 'lastPrice': '115852.98000000', 'lastQty': '0.08558000', 'bidPrice': '115852.97000000', 'bidQty': '2.07940000', 'askPrice': '115852.98000000', 'askQty': '4.56733000', 'openPrice': '115412.50000000', 'highPrice': '117286.73000000', 'lowPrice': '115408.00000000', 'volume': '13019.48550000', 'quoteVolume': '1516617272.31273820', 'openTime': '1758037545013', 'closeTime': '1758123945013', 'firstId': '5237100797', 'lastId': '5239335272', 'count': '2234476'}}
Gia cua btc la: {'symbol': 'BTC/USDT', 'timestamp': 1758123945013, 'datetime': '2025-09-17T15:45:45.013Z', 'high': 117286.73, 'low': 115408.0, 'bid': 115852.97, 'bidVolume': 2.0794, 'ask': 115852.98, 'askVolume': 4.56733, 'vwap': 116488.26463325, 'open': 115412.5, 'close': 115852.98, 'last': 115852.98, 'previousClose': 115412.51, 'change': 440.48, 'percentage': 0.382, 'average': 115632.74, 'baseVolume': 13019.4855, 'quoteVolume': 1516617272.3127382, 'markPrice': None, 'indexPrice': None, 'info': {'symbol': 'BTCUSDT', 'priceChange': '440.48000000', 'priceChangePercent': '0.382', 'weightedAvgPrice': '116488.26463325', 'prevClosePrice': '115412.51000000', 'lastPrice': '115852.98000000', 'lastQty': '0.08558000', 'bidPrice': '115852.97000000', 'bidQty': '2.07940000', 'askPrice': '115852.98000000', 'askQty': '4.56733000', 'openPrice': '115412.50000000', 'highPrice': '117286.73000000', 'lowPrice': '115408.00000000', 'volume': '13019.48550000', 'quoteVolume': '1516617272.31273820', 'openTime': '1758037545013', 'closeTime': '1758123945013', 'firstId': '5237100797', 'lastId': '5239335272', 'count': '2234476'}}

In [45]:
print(type(ticker))
print(ticker['close'])

<class 'dict'>
115852.98

# Chuyen ticker sang dataframe

In [47]:
import pandas as pd
data = pd.DataFrame(ticker)
data

,symbol,timestamp,datetime,high,low,bid,bidVolume,ask,askVolume,vwap,...,last,previousClose,change,percentage,average,baseVolume,quoteVolume,markPrice,indexPrice,info
symbol,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,BTCUSDT
priceChange,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,440.48000000
priceChangePercent,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,0.382
weightedAvgPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,116488.26463325
prevClosePrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,115412.51000000
lastPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,115852.98000000
lastQty,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,0.08558000
bidPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,115852.97000000
bidQty,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,2.07940000
askPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,115852.98000000
askQty,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,4.56733000
openPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,115412.50000000
highPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,117286.73000000
lowPrice,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,115408.00000000
volume,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,13019.48550000
quoteVolume,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,1516617272.31273820
openTime,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,1758037545013
closeTime,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,1758123945013
firstId,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,5237100797
lastId,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,5239335272
count,BTC/USDT,1758123945013,2025-09-17T15:45:45.013Z,117286.73,115408.0,115852.97,2.0794,115852.98,4.56733,116488.264633,...,115852.98,115412.51,440.48,0.382,115632.74,13019.4855,1.516617e+09,None,None,2234476

In [53]:
# Doi vi tri cot
data = data[['close', 'high', 'low', 'open', 'datetime']]
# Doi ten cot
data = data.rename(columns={'close': 'Close', 'high': 'High', 'low': 'Low', 'open': 'Open', 'datetime': 'Datetime'})
data

,Close,High,Low,Open,Datetime
symbol,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
priceChange,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
priceChangePercent,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
weightedAvgPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
prevClosePrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
lastPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
lastQty,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
bidPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
bidQty,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
askPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
askQty,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
openPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
highPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
lowPrice,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
volume,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
quoteVolume,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
openTime,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
closeTime,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
firstId,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
lastId,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z
count,115852.98,117286.73,115408.0,115412.5,2025-09-17T15:45:45.013Z

In [42]:
goihamloadData = loaddataBinance_FromTo('BTC/USDT', '2025-09-17', '2025-09-17', '1m')
print(goihamloadData)

               Datetime       Open       High        Low      Close    Volume
0   2025-09-17 00:00:00  116788.96  116832.00  116788.95  116788.95   7.46106
1   2025-09-17 00:01:00  116788.95  116788.96  116744.09  116769.18   5.31806
2   2025-09-17 00:02:00  116769.18  116769.18  116725.00  116725.00   6.29945
3   2025-09-17 00:03:00  116725.01  116725.01  116720.92  116720.92   1.88384
4   2025-09-17 00:04:00  116720.93  116754.54  116720.92  116754.54   2.96373
..                  ...        ...        ...        ...        ...       ...
898 2025-09-17 14:58:00  115656.34  115656.35  115606.61  115606.61  14.43233
899 2025-09-17 14:59:00  115606.62  115606.62  115606.61  115606.61  12.33158
900 2025-09-17 15:00:00  115606.62  115606.62  115586.30  115604.01  27.83713
901 2025-09-17 15:01:00  115604.01  115604.01  115527.48  115540.00  15.09959
902 2025-09-17 15:02:00  115540.01  115587.13  115540.00  115587.13  16.62355

[903 rows x 6 columns]

In [34]:
print(type(ticker))

<class 'dict'>

# Parse sang DataFrame